#!/bin/bash

# c0ded by : shutdown57 a.k.a alinko
# linuxcode.org - alinkoproject.com
# Script PAIN installer
who=`whoami`
if [[ $who == "root" ]]; then
echo "#! PAIN? Yeah,everyone have the pain but not everyone understand \"what is the pain?\" "
echo "#! In here..."
echo "...I want to teach you about pain #!"
echo "#! Aku tidak sendiri, karena kesendirian selalu bersamaku #!"

echo "[1] Install PaIn"
echo "[2] Uninstall PaIn"
echo -n "install@pain >>"
read enter
if [[ $enter == "1" ]]; then
    mkdir /usr/share/pain
    cp pain.png /usr/share/pain/pain.png
    cp README.md /usr/share/pain/README.md
    echo [Desktop Entry] >> /usr/share/applications/pain.desktop
    echo Terminal=true >> /usr/share/applications/pain.desktop
    echo Type=Application >> /usr/share/applications/pain.desktop
    echo Categories=GNOME\;GTK\;Network\;WebBrowser\; >> /usr/share/applications/pain.desktop
    echo Name=PaIn >> /usr/share/applications/pain.desktop
    echo Comment=Package Installer For Linux Debian based >> /usr/share/applications/pain.desktop
    echo Exec=sudo pain >> /usr/share/applications/pain.desktop
    echo Icon=/usr/share/pain/pain.png >> /usr/share/applications/pain.desktop
	chmod 777 pain
	cp pain /usr/bin/pain
	echo "[DONE] INSTALLATION FINISHED."
	echo "NOW YOU CAN USE \"PAIN\" WITH INPUT COMMAND LIKE : "
	echo "root@pain~# pain "
elif [[ $enter == "2" ]]; then
	rm /usr/share/pain/*
	rm /usr/share/applications/pain.desktop
	rmdir /usr/share/pain
	echo "[DONE] UNINSTALL FINISHED"
fi
else
	echo "You Must Be root! "
fi
