#!/bin/bash

# Script Package installer for debian based
# Debian - Ubuntu - Linux mint - Kali linux - Kubuntu - Lubuntu - Xubuntu - Cyborg  and etc.
# Tested On Linux mint,Ubuntu,Kali linux
# Available package for educational and studying

#color setting
u="\033[4m"
m="\033[1;31m"
k="\033[1;33m"
h="\033[1;32m"
b="\033[1;34m"
n="\033[1;0m"
clear
echo "Checking internet Connection..."
wget -q --tries=10 --timeout=20 --spider http://google.com
if [[ $? -eq 0 ]]; then
        echo -e "[$h OK $n]$u You Are Online"$n
else
        echo -e "[$m KO $n]$u You Are Offline Or Your Connection Too Slow."$n
fi
echo "Press [ENTER] to continue; "
read enter
clear
function Arepo(){

echo -e $m"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo -e $m"!!$k  ____       _         ____  ____                      $m!!"         
echo -e $m"!!$k |  _ \ __ _(_)_ __   / __ \|  _ \ ___ _ __   ___      $m!!"
echo -e $m"!!$k | |_) / _' | | '_ \ / / _' | |_) / _ \ '_ \ / _ \     $m!!"
echo -e $m"!!$k |  __/ (_| | | | | | | (_| |  _ <  __/ |_) | (_) |    $m!!"
echo -e $m"!!$k |_|   \__,_|_|_| |_|\ \__,_|_| \_\___| .__/ \___/     $m!!"
echo -e $m"!!$k                      \____/          |_|              $m!!"
echo -e $m"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"$n
	echo -e $m"[$n 01 $m]$k REPOSITORY UBUNTU TRUSTY (KAMBING.UI.AC.ID)"
	echo -e $m"[$n 02 $m]$k REPOSITORY DEBIAN WHEEZY (KAMBING.UI.AC.ID)"
	echo -e $m"[$n 03 $m]$k REPOSITORY DEBIAN JESSIE (KAMBING.UI.AC.ID)"
	echo -e $m"[$n 99 $m]$k ADVANCED OPTIONS ADD REPOSITORY YOUR SELF "
	echo -n -e $k $u"pain@Repo"$n" >"
	read repo
	if [[ $repo == "01" || $repo == "1" ]]; then
		echo deb http://kambing.ui.ac.id/ubuntu/ trusty main restricted universe multiverse >> /etc/apt/sources.list
		echo deb http://kambing.ui.ac.id/ubuntu/ trusty-updates main restricted universe multiverse >> /etc/apt/sources.list
		echo deb http://kambing.ui.ac.id/ubuntu/ trusty-security main restricted universe multiverse >> /etc/apt/sources.list
		echo deb http://kambing.ui.ac.id/ubuntu/ trusty-backports main restricted universe multiverse >> /etc/apt/sources.list
		echo deb http://kambing.ui.ac.id/ubuntu/ trusty-proposed main restricted universe multiverse >> /etc/apt/sources.list
		sudo apt-get update
	elif [[ $repo == "02" || $repo == "2" ]]; then
		echo deb http://kambing.ui.ac.id/debian/ wheezy main contrib non-free >> /etc/apt/sources.list
		echo deb http://kambing.ui.ac.id/debian/ wheezy-updates main contrib non-free >> /etc/apt/sources.list
		echo deb http://kambing.ui.ac.id/debian-security/ wheezy/updates main contrib non-free >> /etc/apt/sources.list
		sudo apt-get update
	elif [[ $repo == "03" || $repo == "3" ]]; then
		echo deb http://kambing.ui.ac.id/debian/ jessie main contrib non-free >> /etc/apt/sources.list
		echo deb http://kambing.ui.ac.id/debian/ jessie-updates main contrib non-free >> /etc/apt/sources.list
        echo deb http://kambing.ui.ac.id/debian-security/ jessie/updates main contrib non-free >> /etc/apt/sources.list
		sudo apt-get update
	elif [[ $repo == "99" ]]; then
		sudo nano /etc/apt/sources.list
		sudo apt-get update
	else
		clear
		Arepo
	fi
}
function Apain(){
echo -e $h
echo "           /\/|_   ____       ___         __ /\/| "
echo "          |/\/ _| |  _ \ __ _|_ _|_ __   |_ |/\/  "
echo "             | |  | |_) / _' || || '_ \   | |     "
echo "             | |  |  __/ (_| || || | | |  | |     "
echo "             | |  |_|   \__,_|___|_| |_|  | |     "
echo "             |__|                        |__|     "

echo -e $n"        @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo -e $b"        ~[ Package Installer for Debian Based ]~"
echo -e $k"        ~[ Script by : alinko - linuxcode.org ]~"
echo -e $m"        ~[         copyright (c) 2016         ]~"
echo -e $n"        @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo -e $h"[$n 00 $h]$b CHECK AVAILABLE REPOSITORY     $h[$n 10 $h] $b INSTALL UGET DOWNLOADER"
echo -e $h"[$n 01 $h]$b INSTALL GNS3                   $h[$n 11 $h] $b INSTALL BANSHEE MEDIA PLAYER"
echo -e $h"[$n 02 $h]$b INSTALL CISCO PACKETTRACER     $h[$n 12 $h] $b INSTALL GIMP IMAGE MANIPULATION" 
echo -e $h"[$n 03 $h]$b INSTALL EPOPTES                $h[$n 13 $h] $b INSTALL CHEESE CAMERA"
echo -e $h"[$n 04 $h]$b INSTALL SUBLIMETEXT            $h[$n 14 $h] $b INSTALL KAZAM SCREENRECORDER"
echo -e $h"[$n 05 $h]$b INSTALL FIREFOX BROWSER        $h[$n 15 $h] $b INSTALL WINE"
echo -e $h"[$n 06 $h]$b INSTALL CHROMIUM BROWSER       $h[$n 16 $h] $b INSTALL INKSCAPE"
echo -e $h"[$n 07 $h]$b INSTALL LIBREOFFICE            $h[$n 17 $h] $b INSTALL WINBOX (MUST INSTALL WINE)"
echo -e $h"[$n 08 $h]$b INSTALL WPS OFFICE             $h[$n 57 $h] $b ADD REPOSITORY"
echo -e $h"[$n 09 $h]$b INSTALL VIRTUALBOX             $h[$n 58 $h] $b UPDATE"
echo -n -e $k $u"@PaIn"$n" >>" $n
read pil

if [[ $pil == "0" || $pil == "00" ]]; then
	clear
	cat /etc/apt/sources.list
	read enter
	Apain
elif [[ $pil == "1" || $pil == "01" ]]; then
	clear
	echo -e $k"[INSTALL] $h Installing GNS3 In Your System... "$n
	sudo add-apt-repository ppa:gns3/ppa
	sudo apt-get update
	sudo apt-get install gns3 
	echo "Press [ENTER] to continue ;"
	read enter
	Apain
elif [[ $pil == "2" || $pil == "02" ]]; then
 	clear
 	echo -e $k"[INSTALL] $h Installing CISCO PACKETTRACER In Your System..."$n
 	echo "Press [ENTER] to continue;" # belum 
	read enter
	Apain
elif [[ $pil == "3" || $pil == "03" ]]; then
	clear
	echo -e $k"[INSTALL] $h Installing EPOPTES In Your System... "$n
	sudo apt-get install epoptes
	echo "Press [ENTER] to continue;"
	read enter
	Apain
elif [[ $pil == "4" || $pil == "04" ]]; then
	clear
	echo -e $k"[INSTALL] $h Installing SUBLIMETEXT In Your System..."$n
	wget https://download.sublimetext.com/sublime-text_build-3126_i386.deb
	sudo dpkg -i sublime-text_build-3126_i386.deb
	echo "Press [ENTER] to continue;" 
	read enter
	Apain
elif [[ $pil == "5" || $pil == "05" ]]; then
	clear
	echo -e $k"[INSTALL] $h Installing FIREFOX In Your System.."$n
	sudo apt-get install firefox
	echo "Press [ENTER] to continue;"
	read enter
	Apain
elif [[ $pil == "6" || $pil == "06" ]]; then
	clear
	echo -e $k"[INSTALL] $h Installing CHROMIUM In Your System.."$n
	sudo apt-get install chromium-browser
	echo "Press [ENTER] to continue;"
	read enter
	Apain
elif [[ $pil == "7" || $pil == "07" ]]; then
	clear
	echo -e $k"[INSTALL] $h Installing LIBREOFFICE In Your System.."$n
	sudo apt-get install libreoffice
	echo "Press [ENTER] to continue;"
	read enter
	Apain
elif [[ $pil == "8" || $pil == "08" ]]; then
	clear
	echo -e $k"[INSTALL] $h Installing WPS OFFICE In Your System.."$n
	wget http://kdl.cc.ksosoft.com/wps-community/download/a21/wps-office_10.1.0.5672~a21_i386.deb
	sudo dpkg -i wps-office_10.1.0.5672~a21_i386.deb
	echo "Press [ENTER] to continue;" 
	read enter
	Apain
elif [[ $pil == "9" || $pil == "09" ]]; then
	clear
	echo -e $k"[INSTALL] $h Installing VIRTUALBOX In Your System.."$n
	sudo apt-get install virtualbox
	echo "Press [ENTER] to continue;"
	read enter
	Apain
elif [[ $pil == "10" ]]; then
	clear
	echo -e $k"[INSTALL] $h Installing UGET DOWNLOADER In Your System.."$n
	sudo apt-get install uget
	echo "Press [ENTER] to continue;"
	read enter
	Apain
elif [[ $pil == "11" ]]; then
	clear
	echo -e $k"[INSTALL] $h Installing BANSHEE MEDIA PLAYER In Your System.."$n
	sudo apt-get install banshee
	echo "Press [ENTER] to continue;"
	read enter
	Apain
elif [[ $pil == "12" ]]; then
	clear
	echo -e $k"[INSTALL] $h Installing GIMP IMAGE MANIPULATION In Your System.."$n
	sudo apt-get install gimp
	echo "Press [ENTER] to continue;"
	read enter
	Apain
elif [[ $pil == "13" ]]; then
	clear
	echo -e $k"[INSTALL] $h Installing CHEESE CAMERA In Your System.."$n
	sudo apt-get install cheese
	echo "Press [ENTER] to continue;"
	read enter
	Apain
elif [[ $pil == "14" ]]; then
	clear
	echo -e $k"[INSTALL] $h Installing KAZAM SCREENRECORDER In Your System.."$n
	sudo apt-get install kazam
	echo "Press [ENTER] to continue;"
	read enter
	Apain
elif [[ $pil == "15" ]]; then
	clear
	echo -e $k"[INSTALL] $h Installing WINE In Your System.."$n
	sudo apt-get install wine
	echo "Press [ENTER] to continue;"
	read enter
	Apain
elif [[ $pil == "16" ]]; then
	clear
	echo -e $k"[INSTALL] $h Installing INKSCAPE In Your System.."$n
	sudo apt-get install inkscape
	echo "Press [ENTER] to continue;"
	read enter
	Apain
elif [[ $pil == "17" ]]; then
	clear
	echo -e $k"[INSTALL] $h Installing WINBOX In Your System.."$n
	wget http://download2.mikrotik.com/routeros/winbox/3.7/winbox.exe
	wine winbox.exe
	echo "Press [ENTER] to continue;"
	read enter
	Apain
elif [[ $pil == "57" ]]; then
	clear
	Arepo
	echo "Press [ENTER] to continue;"
	read enter
	Apain
elif [[ $pil == "58" ]]; then
	clear
	echo -e $k"UPDATING~..."$n
	sudo apt-get update
	echo "Press [ENTER] to continue;"
	read enter
	Apain
else
	clear
	Apain
fi
	

}
w=`whoami`
if [[ $w == "root" ]]; then
	Apain
else
	echo -e "[$m FAILED $n] Failed to run this applications, you not root  "
	echo -e "[$h + $n] For run this applications you must be root "
	echo -e "[$h + $n] $u Try input command \"sudo su\" and run this!"
	exit
fi
