#!/bin/bash

#################################################
# c0ded by : shutdown57 a.k.a alinko            #
# Copyright (c) 2016 || Nov 15 2016             #
# PaIn (Package Installer) || Debian Based      #
# Version 1.8 codename sadness                  #
# https://github.com/alintamvanz/pain           #
# alinkokomansuby@gmail.com - linuxcode.org     #
#################################################
# You can edit , redistribute and copying This file Under GPL (General Public License v3)

#color setting
u="\033[4m"
m="\033[1;31m"
m2="\033[0;31m"
k="\033[1;33m"
k2="\033[0;33m"
h="\033[1;32m"
h2="\033[0;32m"
b="\033[1;34m"
b2="\033[0;32m"
n="\033[1;0m"
clear
echo "Checking internet Connection..."
wget -q --tries=10 --timeout=20 --spider https://google.com
if [[ $? -eq 0 ]]; then
echo -e $h"__  ______  __  __   ___    ____  ______   ____  _   ____    _____   ________"$n"__   "
echo -e $h"\ \/ / __ \/ / / /  /   |  / __ \/ ____/  / __ \/ | / / /   /  _/ | / / ____"$n"/ /   "
echo -e $h" \  / / / / / / /  / /| | / /_/ / __/    / / / /  |/ / /    / //  |/ / __/ "$n"/ /    "
echo -e $h" / / /_/ / /_/ /  / ___ |/ _, _/ /___   / /_/ / /|  / /____/ // /|  / /___"$n"/_/     "
echo -e $h"/_/\____/\____/  /_/  |_/_/ |_/_____/   \____/_/ |_/_____/___/_/ |_/_____"$n"(_)      "
echo -e $h"                                                                                  "
echo -e $b"+--==[$k2 Yokatta! You now have a internet connection and can install more App $b]==--+"$n
else
echo -e $m"__  ______  __  __  ___   ___  ____$k2  ____  __________   _____  ______     "
echo -e $m"\ \/ / __ \/ / / / / _ | / _ \/ __/$k2 / __ \/ __/ __/ /  /  _/ |/ / __/     "
echo -e $m" \  / /_/ / /_/ / / __ |/ , _/ _/  $k2/ /_/ / _// _// /___/ //    / _/       "
echo -e $m" /_/\____/\____/ /_/ |_/_/|_/___/  $k2\____/_/ /_/ /____/___/_/|_/___/       "
echo -e $m"                                                                          "
echo -e $h"-++==[$k      :( GoodLuck boy! Have nice dream. Oyasuminasai... ):    $h]==++-"$n

fi
echo "Press [ENTER] to continue.."
read enter
clear
Arepo(){

echo -e $m"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo -e $m"!!$k  ____       _         ____  ____                      $m!!"         
echo -e $m"!!$k |  _ \ __ _(_)_ __   / __ \|  _ \ ___ _ __   ___      $m!!"
echo -e $m"!!$k | |_) / _' | | '_ \ / / _' | |_) / _ \ '_ \ / _ \     $m!!"
echo -e $m"!!$k |  __/ (_| | | | | | | (_| |  _ <  __/ |_) | (_) |    $m!!"
echo -e $m"!!$k |_|   \__,_|_|_| |_|\ \__,_|_| \_\___| .__/ \___/     $m!!"
echo -e $m"!!$k                      \____/          |_|              $m!!"
echo -e $m"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"$n
	echo -e $m"[$n 01 $m]$k REPOSITORY UBUNTU TRUSTY (KAMBING.UI.AC.ID)"
	echo -e $m"[$n 02 $m]$k REPOSITORY DEBIAN WHEEZY (KAMBING.UI.AC.ID)"
	echo -e $m"[$n 03 $m]$k REPOSITORY DEBIAN JESSIE (KAMBING.UI.AC.ID)"
	echo -e $m"[$n 04 $m]$k REPOSITORY KALI LINUX (OFFICIAL REPOSITORY)"
	echo -e $m"[$n 99 $m]$k ADVANCED OPTIONS ADD REPOSITORY YOUR SELF "
	echo -n -e $k $u"pain@Repo"$n" >"
	read repo
	if [[ $repo == "01" || $repo == "1" ]]; then
		echo deb http://kambing.ui.ac.id/ubuntu/ trusty main restricted universe multiverse >> /etc/apt/sources.list
		echo deb http://kambing.ui.ac.id/ubuntu/ trusty-updates main restricted universe multiverse >> /etc/apt/sources.list
		echo deb http://kambing.ui.ac.id/ubuntu/ trusty-security main restricted universe multiverse >> /etc/apt/sources.list
		echo deb http://kambing.ui.ac.id/ubuntu/ trusty-backports main restricted universe multiverse >> /etc/apt/sources.list
		echo deb http://kambing.ui.ac.id/ubuntu/ trusty-proposed main restricted universe multiverse >> /etc/apt/sources.list
		sudo apt-get update
	elif [[ $repo == "02" || $repo == "2" ]]; then
		echo deb http://kambing.ui.ac.id/debian/ wheezy main contrib non-free >> /etc/apt/sources.list
		echo deb http://kambing.ui.ac.id/debian/ wheezy-updates main contrib non-free >> /etc/apt/sources.list
		echo deb http://kambing.ui.ac.id/debian-security/ wheezy/updates main contrib non-free >> /etc/apt/sources.list
		sudo apt-get update
	elif [[ $repo == "03" || $repo == "3" ]]; then
		echo deb http://kambing.ui.ac.id/debian/ jessie main contrib non-free >> /etc/apt/sources.list
		echo deb http://kambing.ui.ac.id/debian/ jessie-updates main contrib non-free >> /etc/apt/sources.list
        echo deb http://kambing.ui.ac.id/debian-security/ jessie/updates main contrib non-free >> /etc/apt/sources.list
		sudo apt-get update
	elif [[ $repo == "99" ]]; then
		sudo nano /etc/apt/sources.list
		sudo apt-get update
	else
		clear
		Arepo
	fi
}
ApainBanner(){

	clear
echo -e $m"            __ $k  ____       ___       $m  __              "
echo -e $m"__/\_______| _|$k |  _ \ __ _|_ _|_ __  $m |_ |_______/\__  "
echo -e $m"\    /_____| | $k | |_) / _' || || '_ \ $m  | |_____\    /  "
echo -e $m"/_  _\_____| | $k |  __/ (_| || || | | |$m  | |_____/_  _\  "
echo -e $k"*-"$m"\/"$k"="$b"[$h"+"$b]$m   | | $k |_|   \__,_|___|_| |_|$m  | |   $b[$h"+"$b]"$k"="$m"\/"$k"-*  "
echo -e $k" *-=="$b"[$h"+"$b]$m   |__|$n @Package    @Installer$m |__|   $b[$h"+"$b]"$k"==-*   "
echo -e $k"  *-="$b"[$h"+"$b]                                      $b[$h"+"$b]"$k"=-*    "
echo -e $k"   *-"$b"[$h"+"$b]$h  Codename     :$k sadness              $b[$h"+"$b]"$k"-*     "
echo -e $k"  *-="$b"[$h"+"$b]$h  Version      :$k 1.8                  $b[$h"+"$b]"$k"=-*    "
echo -e $k" *-=="$b"[$h"+"$b]$h  Author       :$k alinko (shutdown57)  $b[$h"+"$b]"$k"==-*   "
echo -e $k"*-==="$b"[$h"+"$b]$h  Site         :$k $u"linuxcode.org"$n        $b[$h"+"$b]"$k"===-*  "
echo -e $n"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"

}
ApainRecommend(){
	ApainBanner
	echo -e $k"[$n 01 $k]$n Banshee             $k[$n 11 $k]$n Inkscape"
	echo -e $k"[$n 02 $k]$n Cairo Dock          $k[$n 12 $k]$n GNS3"
	echo -e $k"[$n 03 $k]$n Docky               $k[$n 13 $k]$n Virtualbox"
	echo -e $k"[$n 04 $k]$n Sublime Text        $k[$n 14 $k]$n Wine"
	echo -e $k"[$n 05 $k]$n Minicom             $k[$n 15 $k]$n Firefox"
	echo -e $k"[$n 06 $k]$n Kazam               $k[$n 16 $k]$n Chrome Browser"
	echo -e $k"[$n 07 $k]$n VLC Media           $k[$n 17 $k]$n LibreOffice"
	echo -e $k"[$n 08 $k]$n Rhythmbox           $k[$n 18 $k]$n WPSOffice"
	echo -e $k"[$n 09 $k]$n Cheese Webcam       $k[$n 19 $k]$n Brasero"
	echo -e $k"[$n 10 $k]$n Gimp                $k[$n 20 $k]$n Ubuntu restricted extras"
	echo -e -n $b"@PaIn:"$k"Recommended$n >>"
	read rec 
	if [[ $rec == "1" || $rec == "01" ]]; then
		xterm -fg blue -title "PaIn : Install Banshee media player.." -e sh -c "apt-get install banshee -y && exit;exec bash" &
		Apain
	elif [[ $rec == "2" || $rec == "02" ]]; then
		xterm -fg orange -title "PaIn : Install Cairo-dock.." -e sh -c "apt-get install cairo-dock -y && exit;exec bash" &
		Apain
	elif [[ $rec == "3" || $rec == "03" ]]; then
		xterm -fg pink -title "PaIn : Install Docky.." -e sh -c "apt-get install docky -y && exit;exec bash" &
		Apain
	elif [[ $rec == "4" || $rec == "04" ]]; then
		bit=`uname -i`
		if [[ $bit == "i686" ]]; then
		xterm -fg lime -title "PaIn : Sublimetext 32bit.." -e sh -c "apt-get install cairo-dock -y && exit;exec bash" &
		Apain
		else
		xterm -fg lime -title "PaIn : Sublimetext 64bit.." -e sh -c "apt-get install cairo-dock -y && exit;exec bash" &
		Apain	
		fi
	elif [[ $rec == "5" || $rec == "05" ]]; then
		xterm -title "PaIn : Minicom.." -e sh -c "apt-get install minicom -y && exit;exec bash" &
		Apain
	elif [[ $rec == "6" || $rec == "06" ]]; then
		xterm -fg orange -title "PaIn : Install Kazam Screenrecorder.." -e sh -c "apt-get install kazam -y && exit;exec bash" &
		Apain
	elif [[ $rec == "7" || $rec == "07" ]]; then
		xterm -fg red -title "PaIn : Install VLC media.." -e sh -c "apt-get install vlc -y && exit;exec bash" &
		Apain
	elif [[ $rec == "8" || $rec == "08" ]]; then
		xterm -fg yellow -title "PaIn : Install Rhythmbox.." -e sh -c "apt-get install rhythmbox -y && exit;exec bash" &
		Apain
	elif [[ $rec == "9" || $rec == "09" ]]; then
		xterm -fg lime -title "PaIn : Install Cheese Webcamera.." -e sh -c "apt-get install cheese -y && exit;exec bash" &
		Apain
	elif [[ $rec == "10" ]]; then
		xterm -fg red -title "PaIn : Install GIMP .." -e sh -c "apt-get install gimp -y && exit;exec bash" &
		Apain
	elif [[ $rec == "11" ]]; then
	    xterm -fg orange -title "PaIn : Install Inkscape.." -e sh -c "apt-get install inkscape -y && exit;exec bash" &
		Apain
	elif [[ $rec == "13" ]]; then
		xterm -fg purple -title "PaIn : Install Virtualbox.." -e sh -c "apt-get install virtualbox -y && exit;exec bash" &
		Apain
	elif [[ $rec == "14" ]]; then
	    xterm -fg yellow -title "PaIn : Install Wine.." -e sh -c "apt-get install wine -y && exit;exec bash" &
		Apain
	elif [[ $rec == "15" ]]; then
		xterm -fg lime -title "PaIn : Install Firefox.." -e sh -c "apt-get install firefox -y && exit;exec bash" &
		Apain
	elif [[ $rec == "16" ]]; then
		xterm -fg white -title "PaIn : Install Chromium.." -e sh -c "apt-get install chromium-browser -y && exit;exec bash" &
		Apain
	elif [[ $rec == "17" ]]; then
		xterm -fg lime -title "PaIn : Install LibreOffice.." -e sh -c "apt-get install libreoffice -y && exit;exec bash" &
		Apain
	elif [[ $rec == "19" ]]; then
		xterm -fg cyan -title "PaIn : Brasero.." -e sh -c "apt-get install brasero -y && exit;exec bash" &
		Apain
	elif [[ $rec == "20" ]]; then
		xterm -fg lime -title "PaIn : Ubuntu Customation kit.." -e sh -c "apt-get install uck -y && exit;exec bash" &
		Apain
	fi
}
ApainAccessoris(){
	ApainBanner
	echo -e $k"[$n 01 $k]$n Cairo Dock"
	echo -e $k"[$n 02 $k]$n Cowsay"
	echo -e $k"[$n 03 $k]$n Docky"
	echo -e $k"[$n 04 $k]$n Flash Player"
	echo -e $k"[$n 05 $k]$n Figlet"
	echo -e $k"[$n 06 $k]$n Gedit"
	echo -e $k"[$n 07 $k]$n Leafpad"
	echo -e $k"[$n 08 $k]$n Plank"
	echo -e $k"[$n 09 $k]$n Virtualbox"
	echo -e -n $b"@PaIn:"$k"Accessoris$n >>"
	read acc
	if [[ $acc == "1" || $acc == "01" ]]; then
		xterm -fg pink -title "PaIn : Install Cairo dock.." -e sh -c "apt-get install cairo-dock -y && exit;exec bash" &
		Apain
	elif [[ $acc == "2" || $acc == "02" ]]; then
		xterm -fg red -title "PaIn : Cowsay.." -e sh -c "apt-get install cowsay -y && exit;exec bash" &
		Apain
	elif [[ $acc == "3" || $acc == "03" ]]; then
		xterm -fg yellow -title "PaIn : Install Docky.." -e sh -c "apt-get install docky -y && exit;exec bash" &
		Apain
	elif [[ $acc == "4" || $acc == "04" ]]; then
		xterm -fg green -title "PaIn : Install Flashplayer.." -e sh -c " null ;exec bash" &
		Apain
	fi
}
ApainEducation(){
	ApainBanner
	echo -e $k"[$n 01 $k]$n GNS3"
	echo -e $k"[$n 02 $k]$n MATE Edu"
	echo -e $k"[$n 03 $k]$n GNOME Edu"
	echo -e -n $b"@PaIn:"$k"Education$n >>"
	read edu
}
ApainMedia(){
	ApainBanner
	echo -e $k"[$n 01 $k]$n Banshee"
	echo -e $k"[$n 02 $k]$n Brasero"
	echo -e $k"[$n 03 $k]$n Cheese"
	echo -e $k"[$n 04 $k]$n Kazam"
	echo -e $k"[$n 05 $k]$n VLC Media"
	echo -e $k"[$n 06 $k]$n Rhythmbox"
	echo -e -n $b"@PaIn:"$k"SoundVIdeo$n >>"
	read sv
	if [[ $sv == "1" || $sv == "01" ]]; then
		xterm -fg blue -title "PaIn : Install Banshee media player.." -e sh -c "apt-get install banshee -y && exit;exec bash" &
		Apain
	elif [[ $sv == "2" || $sv == "02" ]]; then
		xterm -fg pink -title "PaIn : Install Brasero..." -e sh -c "apt-get install brasero -y && exit;exec bash" &
		Apain
	elif [[ $sv == "3" || $sv == "03" ]]; then
	   xterm -fg red -title "PaIn : Install Cheese Webcamera.." -e sh -c "apt-get install cheese -y && exit;exec bash" &
		Apain
	elif [[ $sv == "4" || $sv == "04" ]]; then
	   xterm -fg lime -title "PaIn : Install Kazam Screenrecorder.." -e sh -c "apt-get install kazam -y && exit;exec bash" &
		Apain
	elif [[ $sv == "5" || $sv == "05" ]]; then
		xterm -fg yellow -title "PaIn : Install VLC media Player.." -e sh -c "apt-get install vlc -y && exit;exec bash" &
		Apain
	elif [[ $sv == "6" || $sv == "06" ]]; then
	   xterm -fg orange -title "PaIn : Install Rhythmbox.." -e sh -c "apt-get install rhythmbox -y && exit;exec bash" &
		Apain
	else
		Apain
	fi
}
ApainGraphics(){
	ApainBanner
	echo -e $k"[$n 01 $k]$n Gimp"
	echo -e $k"[$n 02 $k]$n ImageMagick"
	echo -e $k"[$n 03 $k]$n Inkscape"
	echo -e -n $b"@PaIn:"$k"Graphics$n >>"
	read grp
	if [[ $grp == "1" || $grp == "01" ]]; then
		xterm -fg blue -title "PaIn : Install GIMP Image Manipulation.." -e sh -c "apt-get install gimp -y && exit;exec bash" &
		Apain
	elif [[ $grp == "2" || $grp == "02" ]]; then
	  xterm -fg cyan -title "PaIn : Install ImageMagick.." -e sh -c "apt-get install imagemagick -y && exit;exec bash" &
		Apain
	elif [[ $grp == "3" || $grep == "03" ]]; then
		xterm -fg red -title "PaIn : Install Inkscape.." -e sh -c "apt-get install Inkscape -y && exit;exec bash" &
		Apain
	else
		Apain

	fi
}
ApainOffice(){
	ApainBanner
	echo -e $k"[$n 01 $k]$n LibreOffice"
	echo -e $k"[$n 02 $k]$n WPS Office"
	echo -e -n $b"@PaIn:"$k"Office$n >>"
	read off
}
ApainProgram(){
	ApainBanner
	echo -e $k"[$n 01 $k]$n Bluefish"
	echo -e $k"[$n 02 $k]$n Sublime text"
	echo -e $k"[$n 03 $k]$n Webserver (Lampp)"
	echo -e  -n $b"@PaIn:"$k"Programming$n >>"
	read prog
}
ApainSystem(){
	ApainBanner
	echo -e $k"[$n 01 $k]$n Unetbootin "
	echo -e $k"[$n 02 $k]$n Remastersys "
	echo -e $k"[$n 03 $k]$n Ubuntu Customation kit"
	echo -e $k"[$n 04 $k]$n Gparted "
	echo -e $k"[$n 05 $k]$n Gnome tweak tools "
	echo -e $k"[$n 06 $k]$n Mate tweak tools"
	echo -e -n $b"@PaIn:"$k"SystemTools$n >>"
	read sis
}
Apain(){
ApainBanner
echo -e $h"[$n 01 $h]$b CHECK AVAILABLE REPOSITORY$k2 ~"
echo -e $h"[$n 02 $h]$b Accessoris                $k2 ~"
echo -e $h"[$n 03 $h]$b Education                 $k2 ~" 
echo -e $h"[$n 04 $h]$b Graphics                  $k2 ~"
echo -e $h"[$n 05 $h]$b Office                    $k2 ~"
echo -e $h"[$n 06 $h]$b Other                     $k2 ~"
echo -e $h"[$n 07 $h]$b Programming               $k2 ~"
echo -e $h"[$n 08 $h]$b Sound & Video             $k2 ~"
echo -e $h"[$n 09 $h]$b System Tools              $k2 ~"
echo -e $h"[$n 10 $h]$b Recommended applications  $k2 ~"
echo -e $h"[$n 11 $h]$b Fix Error                 $k2 ~"
echo -n -e $k $u"@PaIn"$n" >>" $n
read pil
if [[ $pil == "1" || $pil == "01" ]]; then
	xterm -fg lime -title "REPOSITORY IN YOUR SYSTEM" -e sh -c "more /etc/apt/sources.list && read enter && exit;exec bash" &
	Apain
elif [[ $pil == "2" || $pil == "02" ]]; then
    ApainAccessoris
    Apain
 elif [[ $pil == "3" || $pil == "03" ]]; then
 	ApainEducation
 	Apain
 elif [[ $pil == "4" || $pil == "04" ]]; then
    ApainGraphics
    Apain
elif [[ $pil == "5" || $pil == "05" ]]; then
    ApainOffice
    Apain
elif [[ $pil == "7" || $pil == "07" ]]; then
    ApainProgram
    Apain
elif [[ $pil == "8" || $pil == "08" ]]; then
    ApainMedia
    Apain
elif [[ $pil == "9" || $pil == "09" ]]; then
    ApainSystem
    Apain
elif [[ $pil == "10" ]]; then
    ApainRecommend
    Apain
elif [[ $pil == "11" ]]; then
    xterm -fg red -title "PaIn :Fix Error" -e sh -c "apt-get -f install -y && apt-get update --fix-missing -y && apt-get autoremove -y && exit ;exec bash" &    
 else
 	Apain
fi
}
w=`whoami`
if [[ $w == "root" ]]; then
	Apain
else
	echo -e "[$m FAILED $n] Failed to run this applications, you not root  "
	echo -e "[$h + $n] For run this applications you must be root "
	echo -e "[$h + $n] $u Try input command \"sudo pain\""
	exit
fi
